### ISSUE TITLE
Implementacia GUI

### ISSUE THREAD

**Issue by Kjub** [TIS2018-FMFI/trener-slov#14]

**Comment by LukasBacon** [comment]
Dalej treba spravit datovu triedu Group Serializable aby som mohol spravit dragAndDrop v GroupListe.
Skupinu treba ulozit do ClipBoardu ked sa dragne a vie uozit iba String.

**Comment by LukasBacon** [comment]
Import a Export sa daju ovladat pomocou GUI.

**Comment by LukasBacon** [comment]
Do abstrakten triedy GameMode.java som pridal abstraktnu metodu reinitialize(), ktora znovu reinicializuje mod a pripravy polozky na znovuspustenie modu.
