### ISSUE TITLE
Testovacie scenáre

### ISSUE THREAD

**Issue by Kothy** [TIS2018-FMFI/trener-slov#23]
vytvorila som dokument testovacie scenáre a napísala som zatiaľ ako budem testovať svoju časť, podopisujte tam svoje časti a potom sa pustím do tých scenárov, ktoré sú z katalógu

**Comment by Kothy** [comment]
pridala som testovacie scenáre z katalógu požiadaviek, pozriete prosím, či som to napísala dobre, poprípade to nejako prepíšte alebo zmeňte ak treba

**Comment by Kothy** [comment]
a dopíšte tam svoje časti - ako budete testovať to, čo naprogramujete

**Comment by LukasBacon** [comment]
Do dokumentu som pridal testovacie scenáre pre Gui.
