### ISSUE TITLE
Dokončenie dokumentácie

### ISSUE THREAD

**Issue by Kothy** [TIS2018-FMFI/trener-slov#57]

**Comment by LukasBacon** [comment]
Ked bude hotova implementacia tak by kazdy mohol dorobit diagram, ktory robil tak aby zodpovedal finalnej appke. Teda ja class diagram, Klaudia component diagram, Jan state diagram a Jakub moqups.

**Comment by Kothy** [comment]
Lukáš - o mojom komponent diagrame sa s vami potrebujem ešte poradiť, ako presne ste to naprogramovali

**Comment by LukasBacon** [comment]
Tak komponent az po class diagrame.

**Comment by Kothy** [comment]
pridávam aj návod na použitie
