### ISSUE TITLE
Component diagram

### ISSUE THREAD

**Issue by LukasBacon** [TIS2018-FMFI/trener-slov#7]

**Comment by Kothy** [comment]
Zmeny som nahrala do návrhu

**Comment by LukasBacon** [comment]
A ešte jedna vecička ma napadla.
MainController bude komunikovať s DataControllerom a FileManagerom.
Napr. keď si bude pýtať lekcie a obrázky pre GUI alebo posielať nejaké požiadavky na pridanie alebo vymazanie nejakých dát.

**Comment by LukasBacon** [comment]
Treba to treba opravit.
- odstranit userov

**Comment by Kothy** [comment]
upravila som diagram a vložila do návrhu
