### ISSUE TITLE
Class diagram

### ISSUE THREAD

**Issue by LukasBacon** [TIS2018-FMFI/trener-slov#8]

**Comment by LukasBacon** [comment]
Pracujem na class diagrame.
Mám takú vec, na ktorej by sme sa mali dohodnúť.
Budeme mať názvy v kóde po anglicky alebo po slovensky ?
Budú Lesson, getLesson(), getGroup(), Item
alebo Lekcia, getLekcia(), getSkupina(), Polozka ?
Ja som za anglické názvy, pretože sa mi nepáči ako sa dva jazyky motajú.

**Comment by Kothy** [comment]
som za anglické tak isto, aj to lepšie vyzerá :)
